name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 23.5.0
          cache: 'yarn'

      # Install the required Yarn version (from package.json)
      - name: Install Yarn 4.5.3
        run: |
          npm install -g yarn@4.5.3

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Run test
      - name: Run Test
        run: yarn run test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 23.5.0
          cache: 'yarn'

      # Install the required Yarn version (from package.json)
      - name: Install Yarn 4.5.3
        run: |
          npm install -g yarn@4.5.3

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Run lint
      - name: Run Lint
        run: yarn run lint
