name: PR (CI) Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NX_TODO_BACKEND_HOST: http://localhost:8080
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.API_REPO_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Web Repo
        uses: actions/checkout@v3

      - name: Checkout API Repo
        uses: actions/checkout@v3
        with:
          repository: nm123github/todos-backend
          ref: main
          ssh-key: ${{ secrets.API_REPO_DEPLOY_KEY }}
          path: api-repo

      - name: Set up Docker Compose
        run: |
          # Bring up Docker Compose services
          docker compose -f docker-compose.yml -f api-repo/docker-compose.yml up -d

      - name: Docker Logs
        run: |
          docker-compose logs

      - name: Wait for Backend
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:8080/task; do sleep 2; done'

      - name: Corepack Enable
        run: |
          # Corepack enable for yarn version 4.5.3
          corepack enable && corepack prepare yarn@4.5.3 --activate

      - name: Install Dependencies
        run: |
          yarn install --immutable

      - name: Install Playwright
        run: |
          yarn playwright install --with-deps chromium

      - name: Run Playwright Tests
        run: |
          yarn e2e

      - name: Clean Up
        run: docker compose down
